version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cnpj_postgres
    restart: always
    environment:
      POSTGRES_USER: cnpjuser
      POSTGRES_PASSWORD: cnpjpass
      POSTGRES_DB: cnpjdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
