name: CI/CD

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches-ignore: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...